### ISSUE TITLE
Server side error... 

### ISSUE THREAD

**Issue by victorbstan** [edwardhotchkiss/mongoose-paginate#44]
I'm using `mongoose-paginate@3.1.5` and I'm getting the server side error. I'm not sure why it's occurring... 

```
/node_modules/mongoose-paginate/lib/mongoose-paginate.js:55
    callback(null, data.results, Math.ceil(data.count / resultsPerPage) || 1,
    ^
TypeError: object is not a function
    at .../node_modules/mongoose-paginate/lib/mongoose-paginate.js:55:5
    at .../node_modules/mongoose-paginate/node_modules/async/lib/async.js:682:13
    at .../node_modules/mongoose-paginate/node_modules/async/lib/async.js:49:16
    at done (.../node_modules/mongoose-paginate/node_modules/async/lib/async.js:239:19)
    at .../node_modules/mongoose-paginate/node_modules/async/lib/async.js:40:16
    at Promise.<anonymous> (.../node_modules/mongoose-paginate/node_modules/async/lib/async.js:679:17)
    at Promise.<anonymous> (.../node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (...node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (.../node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (.../node_modules/mongoose/lib/promise.js:114:23)
    at Promise.<anonymous> (...node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (.../node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (.../node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at .../node_modules/mongoose/lib/query.js:1058:26
```

**Comment by victorbstan** [comment]
Query signature updated
